markdown:     kramdown
highlighter:  rouge

title:        Patrick Berry
tagline:      'Portfolio'
description:  'Personal portfolio site for Patrick Berry'

sass:
    load_paths:
        - _sass
        - node_modules

exclude: []

collections_dir: collections

collections:
    projects:
        output: true
    interests:
        output: true

plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-tagging-related_posts
  - jekyll-analytics

disqus:
  shortname: patrickcberry

sidebar_home_link: true
sidebar_blog_link: /blog.html

# Pagination Settings
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
#  title_suffix: ' - page :num'   # title_suffix depreciated
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Produces a cleaner folder structure when using categories
permalink: /:year/:month/:title.html

# Google Analytics
jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-117119213-1      # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking
